# Beyond the Burn -- Regionals, Media, and Volunteering

## Regionals

### Attended any regional Burning Man events/mixers/gatherings



### Ivolvement with a regional Burning Man event



## Burning Man Media

### Media managed by Burning Man Project



### Media not managed by Burning Man Project



### Most valuable types of information coming from Burning Man Project



### Listened to BMIR (Burning Man Information Radio) this year



## Volunteerism and donations

### Volunteered in the last year



### Approximate average hours per month spent on volunteer efforts last year



### Made a charitable donation in the last year



### Inspiration to volunteer, donate, or get involved after going to Black Rock City


## New skills


### Inspiration to practice skills after going to Black Rock City



### Skills proved useful in the default world



### Using skills outside Black Rock City



### Impact of new skills outside of Black Rock City




