# Perspectives on Burning Man

## Burner Identity and the 10 Principles 

### Do you identify as a Burner?



### Which of the Ten Principles are the most difficult to practice in every day life
```{r}
prinDif <- makePlotData(varNames = list(c("princd_incl", "princd_gift", 
                                          "princd_decom", "princd_reli", 
                                          "princd_expr", "princd_commu",
                                          "princd_resp", "princd_lnt", 
                                          "princd_part", "princd_immed"),
                                        c("princd_incl", "princd_gift", 
                                          "princd_decom", "princd_reli", 
                                          "princd_expr", "princd_commu",
                                          "princd_resp", "princd_lnt", 
                                          "princd_part", "princd_immed"),
                                        c("princd_incl", "princd_gift", 
                                          "princd_decom", "princd_reli", 
                                          "princd_expr", "princd_commu",
                                          "princd_resp", "princd_lnt", 
                                          "princd_part", "princd_immed"),
                                        c("princd_incl", "princd_gift", 
                                          "princd_decom", "princd_reli", 
                                          "princd_expr", "princd_commu",
                                          "princd_resp", "princd_lnt", 
                                          "princd_part", "princd_immed"),
                                        c("tenPrinciplesDifficult.radicalInclusion",  
                                          "tenPrinciplesDifficult.gifting",             
                                          "tenPrinciplesDifficult.decommodification",
                                          "tenPrinciplesDifficult.radicalSelfReliance",  
                                          "tenPrinciplesDifficult.radicalSelfExpression", 
                                          "tenPrinciplesDifficult.communalEffort",       
                                          "tenPrinciplesDifficult.civicResponsibility", 
                                          "tenPrinciplesDifficult.leaveNoTrace",         
                                          "tenPrinciplesDifficult.participation",       
                                          "tenPrinciplesDifficult.immediacy")),
                        designs = list(design16, design17, design18, 
                                       design19, design22),
                        years = c(2016:2019, 2022), 
                        levels = list("yes", "yes", "yes", "yes", TRUE),
                        labels = c("Radical Inclusion", "Gifting",
                                   "Decommodification", "Radical Self-reliance",
                                   "Radical Self-expression", "Communal Effort", 
                                   "Civic Resposibility","Leave No Trace", 
                                   "Participation", "Immediacy"),
                        labelOrder = c(3, 10, 5, 2, 8, 1, 6, 7, 9, 4))

ggplot(prinDif, aes(x = year, y = est, color = labels)) +
  geom_line(linewidth = 1.5) +
  geom_point(size = 2.25, color = "black") +
  geom_errorbar(aes(ymin = lower, ymax = upper), color = "black", width = 0.2,
                linewidth = 1.25) +
  theme_bw(13) +
  theme(panel.grid.minor = element_blank()) +
  # scale_color_brewer(type = "seq", palette = 11) +
  scale_x_continuous(breaks = c(2013:2019, 2022), labels = c(2013:2019, 2022)) +
  scale_y_continuous(labels = percent) +
  labs(x = "Year", y = "Percent of Burners at BRC in 2022")

ggplot(prinDif[prinDif$year == 2022,], aes(y = est, x = labels)) +
  geom_bar(stat = "identity") +
  theme_bw(13) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_y_continuous(labels = percent)
```

### Importance of the 10 Principles



### Ten principles essential to creating an authentic Burning Man experience



### Incorporating the 10 principles in the workplace



## Children at Burning Man

### Have you ever brought children under 18 to Black Rock City?


### Do you think that Burning Man event attendance should be restricted to participants aged 18 or older?


## Burning Man Project's Nonprofit Activites

### Familiarity with programs annd affiliiates of the nonprofit Burning Man Project



### Should the Burning Man Project be involved in faciliating and producing year-round activites?



### How would you distribute $1,000 to donate to programs of the nonprofit Burning man Project?



## Sustainability

### What new sustainability projects did you notice while in BRC this year?



### How did you (and your camp or project) begin to address sustainability in Black Rock City?



### How important to you is it that the Burning Man Project visibly engages in best practices in environmental sustainability?  



## Radical Inclusion, Diversity, and Equity (R.I.D.E.)

### How did you see R.I.D.E. in action while in BRC 



### How did you personally work to create a more diverse and welcoming Black Rock City?



